### ISSUE TITLE
TypeScript definition

### ISSUE THREAD

**Issue by blakeembrey** [matthewmueller/envobj#1]
I've been using the project and defined a TypeScript definition for use, would you be interested in having it inside the repo? It wouldn't affect any of the project, but it would allow TypeScript users to start using it right away and get type information. I'd be happy to help maintain it too.

For reference, this is the definition I'm using: https://github.com/typed-typings/npm-envobj/blob/master/index.d.ts.

**Comment by matthewmueller** [comment]
definitely 👍

**Comment by blakeembrey** [comment]
@matthewmueller Any chance of a release with the definition? 😄

**Comment by matthewmueller** [comment]
woops, sorry for the delay! just released 1.0.4

**Comment by blakeembrey** [comment]
I don't actually see it updated on NPM yet, might need to try again: https://www.npmjs.com/package/envobj

**Comment by matthewmueller** [comment]
Woops! Okay should be up now!
