### ISSUE TITLE
[feature] format output

### ISSUE THREAD

**Issue by yoshuawuyts** [matthewmueller/envobj#2]
https://github.com/inxilpro/node-checkenv is doing a pretty solid job, but it all needs to be compiled down and only reads from files; would be cool if we could copy some stuff from it :zap:

**Comment by matthewmueller** [comment]
oh yah, that's pretty neat. I have something that just prints out env variables if you want that:

```js
function stringify (env) {
  let out = []
  for (let key in env) {
    let value = typeof env[key] === 'string' ? `"${env[key]}"` : env[key]
    out.push(`  → ${key} = ${value}`)
  }
  return out.sort().join('\n')
}
```

like this: 

![img](https://www.dropbox.com/s/5lda2snqvtjxj02/Screenshot%202016-08-28%2016.34.46.png?dl=0)
