### ISSUE TITLE
1.x compatibility helper

### ISSUE THREAD

**Issue by lyricnz** [matthewmueller/envobj#6]
Since envobj changed the API from https://www.npmjs.com/package/envobj/v/1.0.5 to https://www.npmjs.com/package/envobj/v/2.0.0 to require explicit schema and sources, it would be useful to provide a backward-compatible version.

**Comment by lyricnz** [comment]
A crude example:
`// envobj 1.x compatibility
function makeEnvObj(defaults) {
  const schema = {};
  const newDefaults = {};
  for (const [key, value] of Object.entries(defaults)) {
    schema[key] = (typeof value in TYPE_MAP) ? TYPE_MAP[typeof value] : envobj.string;
    newDefaults[key] = String(value);
  }
  return envobj.envobj(schema, process.env, newDefaults);
}
`

**Comment by blakeembrey** [comment]
The point of the 2.0 was to be explicitly backward incompatible, otherwise it could have been released as 1.x. Feel free to use that in your apps, but it won't be added to the source due to other backward incompatibilities (e.g. the error instance that's used).

**Comment by lyricnz** [comment]
The problem is, for me, that we have a potentially big config structure that has to be duplicated (and aligned) between two declarations.  Our app, for example, has 60 configuration items, nearly all of which have defaults.

**Comment by blakeembrey** [comment]
I’m not sure I understand the problem you’re having though. You’re welcome to stay on V1. I also use this package in at least a dozen projects, I’ll just be iteratively updating when I get a chance to V2.

**Comment by blakeembrey** [comment]
Closing this out since you can stick with 1.x until you're happy with migrating. Definitely understand it can take time 👍
